- file_path: ${MASTER_DATA_SETUP_FILE_PATH}
  sheet_name: InternalSuspendedList
  columns:
    - name: ID
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}

    - name: Debtor type
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}
        - type: value_list
          values: [Individual, Company]
    
    # - name: [Debtor type, NRIC/FIN]
    #   rules:
    #     - type: unique
    
    # - name: [Debtor type, UEN]
    #   rules:
    #     - type: unique
    
    - name: NRIC/FIN
      rules:
        - type: unique
        - type: inner_reference
          ref_info:
            - condition:
                operator: OR
                conditions:
                - column: Debtor type
                  operator: ==
                  values: Individual
              ref_rules:
              - type: mandatory
                empty_list: ${EMPTY_LIST}
                message: "NRIC/FIN is required if Debtor type is Individual"

    - name: UEN
      rules:
        - type: unique
        - type: inner_reference
          ref_info:
            - condition:
                operator: OR
                conditions:
                - column: Debtor type
                  operator: ==
                  values: Company
              ref_rules:
              - type: mandatory
                empty_list: ${EMPTY_LIST}
                message: "UEN is required if Debtor type is Company"

    - name: Effective from
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}
        - type: datetime_format
          format: "%d/%m/%Y"
        - type: datetime_range
          format: "%d/%m/%Y"
          start_date: 01/01/1900
          end_date: 01/01/2029
        - type: datetime_logic
          left_column: "Effective from"
          right_column: "Effective to"
          format: "%d/%m/%Y"

    - name: Effective to
      rules:
        - type: datetime_format
          format: "%d/%m/%Y"
        - type: datetime_range
          format: "%d/%m/%Y"
          start_date: 01/01/1900
          end_date: 01/01/2029

    - name: Bad debt write-off amount
      rules:
        - type: data_type
          data_type: numeric
        - type: in_range_number
          min_value: 0
          max_value: 1000000

    - name: Suspended reason
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}
        - type: in_range_string_length
          min_length: 1
          max_length: 255
        - type: outer_reference
          ref_info:       # Cross-file FK check
            - condition:
                operator: AND
                conditions:
                - file_path: ${MASTER_DATA_SETUP_FILE_PATH}
                  sheet_name: SuspensionReason
                  column: Suspension reason name  # Must match another column `name`
                  operator: OR
                  conditions:
                    - operator: AND
                      conditions:
                      # - column: Status
                      #   operator: ==
                      #   values: Active
                      - column: Suspension reason name
                        operator: "not in"
                        values: ${EMPTY_LIST}
                # - file_path: "${FILE_PATH}" #${DATA_FOLDER_PATH}/${MASTER_DATA_SETUP_FILE_NAME}
                #   sheet_name: InternalSuspendedList
                #   column: Status  # Must match another column `name`
                #   operator: OR
                #   conditions:
                #       - column: Source
                #         operator: ==
                #         values: Auto
              ref_rules:
                - type: value_list # outer reference maybe has 2 rule: value list and mandatory
                  values: ${VALUE_LIST}
                  message: Suspended reason must be in values of file '${MASTER_DATA_SETUP_FILE_PATH}' -> sheet 'SuspensionReason' -> column 'Suspension reason name'
    
    - name: Source
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}
        - type: value_list
          values: [Auto, Manual]
    
    - name: Status
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}
        - type: value_list
          values: [Active, Inactive]
    
    - name: Created On
      rules:
        - type: datetime_logic
          left_column: Created On
          right_column: Modified On
          format: "%d/%m/%Y %H:%M:%S"

- file_path: ${MASTER_DATA_SETUP_FILE_PATH}
  sheet_name: SuspensionReason
  columns:
    - name: Suspension reason name
      rules:
        - type: mandatory
          empty_list: ${EMPTY_LIST}