- file_path: ${FILE_PATH}
  sheet_name: ${SHEET_NAME}
  columns:
    - name: User ID
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Name
      rules:
        - type: remove_white_space
          processing_action: preprocessing
    
    - name: Gender
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${GENDER_ENUM}
          processing_action: postprocessing
    
    - name: Date of birth
      rules:
        - type: remove_white_space
          processing_action: preprocessing
    
    - name: Residential status
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${RESIDENTIAL_STATUS_ENUM}
          processing_action: postprocessing
    
    - name: NRIC/FIN
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Pass type
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${PASS_TYPE_ENUM}
          processing_action: postprocessing
        - type: fill_default
          default_value: "None"
          processing_action: postprocessing
          # condition:
          #   operator: OR
          #   conditions:
          #     - column: Residential status
          #       operator: "!="
          #       values: Foreigner

    - name: Pass expiry date
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Work permit ID
      rules:
        - type: remove_white_space
          processing_action: preprocessing
    
    - name: Race
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${RACE_ENUM}
          processing_action: postprocessing
    
    - name: Country/Region of birth
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${COUNTRY_ENUM}
          processing_action: postprocessing
    
    - name: Nationality
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${NATIONALITY_ENUM}
          processing_action: postprocessing

    - name: Employee ID
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Residential address
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${RESINDETAL_ADDRESS_ENUM}
          processing_action: postprocessing
    
    - name: Country or region
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${COUNTRY_ENUM}
          processing_action: postprocessing
    
    - name: Postal code
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Block/Building No.
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Building name
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Street name
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Floor number
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: data_type
          data_type: integer
          processing_action: preprocessing
        - type: convert_data_type
          data_type: integer
          processing_action: postprocessing

    - name: Unit number
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: data_type
          data_type: integer
          processing_action: preprocessing
        - type: convert_data_type
          data_type: integer
          processing_action: postprocessing

    - name: Floor/Unit number is not applicable 
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${NO_FLOOR_OR_UNIT_NUMER_ENUM}
          processing_action: postprocessing

    - name: Address line 1
      rules:
        - type: remove_white_space
          processing_action: preprocessing

    - name: Address line 2
      rules:
        - type: remove_white_space
          processing_action: preprocessing
    
    - name: Employed
      rules:
        - type: string_case
          case_type: lower
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${EMPLOYED_ENUM}
          processing_action: postprocessing

    - name: Designation
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: fill_default
          default_value: "None"
          processing_action: postprocessing
        - type: enum_mapping
          enum_values: ${DESIGNATION_ENUM}
          processing_action: postprocessing

    - name: Basic salary
      rules:
        - type: remove_white_space
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${BASIC_SALARY_ENUM}
          processing_action: postprocessing

    - name: VIP
      rules:
        - type: string_case
          case_type: lower
          processing_action: preprocessing
        - type: enum_mapping
          enum_values: ${VIP_ENUM}
          processing_action: postprocessing