# ============================== InternalSuspendedList ==============================
- file_path: ${MASTER_DATA_FILE_PATH}
  sheet_name: InternalSuspendedList
  columns:
    - name: Bad debt write-off amount
      rules:
        - type: convert_data_type
          data_type: numeric
          decimal_places: 4
          processing_action: postprocessing
        - type: remove_white_space
          processing_action: preprocessing

    - name: Effective from
      rules:
        - type: remove_white_space
          processing_action: preprocessing


# ============================== SuspensionReason ==============================
- file_path: ${MASTER_DATA_FILE_PATH}
  sheet_name: SuspensionReason
  columns:
    - name: Status
      rules:
        - type: remove_white_space
          processing_action: preprocessing