files:
# File 1: InternalSuspendedList
- sheet_name: InternalSuspendedList
  file_path: ${DATA_FOLDER_PATH}/InternalSuspendedList.parquet
  file_type: parquet
  report_file_path: ${DATA_FOLDER_PATH}/InternalSuspendedList_report.xlsx

  columns:
    - name: ID
      data_type: string
      required: true
      skip_if_null: false
      rules:
        - type: mandatory
        - type: unique

    - name: Debtor type
      data_type: string
      required: true
      skip_if_null: false
      rules:
        - type: value_list
          values:
          - Individual
          - Company

    - name: NRIC/FIN
      data_type: string
      required: true
      skip_if_null: false
      rules:
        - type: unique
        - type: inner_reference
          ref_info:
            - condition:
                operator: AND
                conditions:
                - column: Debtor type
                  operator: ==
                  values: Individual
                - column: Status
                  operator: ==
                  values: Active
              ref_rules:
                - type: mandatory

    - name: Suspended reason
      data_type: string
      required: true
      skip_if_null: false
      rules:
        - type: mandatory
        - type: outer_reference
          ref_info:       # Cross-file FK check
            - condition:
                operator: OR
                conditions:
                - file_path: "/home/user/data-da-ds-de/data_validation_pandas/data_test/raw/parquet/2026-02-06/Data Template 03_Master Data Setup_SLP3P4 1/SuspensionReason.parquet" #${DATA_FOLDER_PATH}/SuspensionReason.parquet
                  sheet_name: SuspensionReason
                  column: Suspension reason name  # Must match another column `name`
                  operator: OR
                  conditions:
                    - operator: AND
                      conditions:
                      - column: Status
                        operator: ==
                        values: Active
                      - column: Suspension reason name
                        operator: "!="
                        values: ["", "N/A", "nan", "null"]
                # - file_path: ${DATA_FOLDER_PATH}/CourseCategory.parquet
                #   sheet_name: CourseCategory
                #   column_name: Course category name  # Must match another column `name`
                #   filters:
                #     - operator: AND
                #       conditions:
                #       - column: Status
                #         operator: ==
                #         values: Active
              ref_rules:
                - type: mandatory

    - name: Effective from
      data_type: date
      required: true
      skip_if_null: false
      rules:
        - type: mandatory
        - type: date_format
          format: "%d/%m/%Y"
        - type: date_range
          min: "01/01/1900"
          max: "31/12/2099"

    - name: Bad debt write-off amount
      data_type: float
      required: false
      skip_if_null: true
      rules:
        - type: numeric_range
          min: 0
          max: 999999.99
        - type: decimal_precision
          decimals: 2

    - name: Status
      data_type: string
      required: true
      skip_if_null: false
      rules:
        - type: mandatory
        - type: value_list
          values:
            - Active
            - Inactive
